/**
 * @file localization_estimate_msg.h
 * @brief Defines the localization estimate message
 *
 * This file provides the definition for a localization estimate message.
 */
#pragma once

#include "common_types/header.h"
#include "common_types/pose.h"
#include "common_types/twist.h"
#include "msg/declare_msg.h"

namespace msg
{
  /**
   * @brief Represents an estimate of the robot's localization (position and orientation)
   *        and velocity (linear and angular).
   *
   * This message combines pose and twist information, typically generated by
   * localization algorithms like Kalman filters or particle filters.
   * It includes covariance matrices to represent the uncertainty associated
   * with the estimates.
   */
  DECLARE_MESSAGE_TYPE(LocalizationEstimateMsg)
  {
    /**
     * @brief Header containing timestamp and frame ID information.
     *
     * The header provides context for the localization estimate, specifying
     * when the estimate was generated and in which coordinate frame it is expressed.
     */
    Header header;

    /**
     * @brief Estimated pose (position and orientation) with covariance.
     *
     * This field contains the estimated position and orientation of the robot,
     * along with a covariance matrix representing the uncertainty of this estimate.
     */
    PoseWithCovariance est_pose;

    /**
     * @brief Estimated twist (linear and angular velocity) with covariance.
     *
     * This field contains the estimated linear and angular velocity of the robot,
     * along with a covariance matrix representing the uncertainty of this estimate.
     */
    TwistWithCovariance est_twist;
  };
} // namespace msg
